name = "letsorder-admin"
compatibility_date = "2024-01-01"

[env.production]
  # Production environment configuration
  vars = { NODE_ENV = "production" }

[env.staging]
  # Staging environment configuration  
  vars = { NODE_ENV = "staging" }

# Build configuration
[build]
  command = "npm run build"
  publish = "dist"

# CloudFlare Pages Functions (if needed)
[functions]
  directory = "functions"

# Custom domains (to be configured in CloudFlare Pages dashboard)
# routes = [
#   { pattern = "admin.letsorder.com", zone_name = "letsorder.com" }
# ]