# Cargo audit configuration
# Temporary ignore for RUSTSEC-2023-0071 in rsa crate
# This is pulled in by sqlx-mysql but we only use SQLite
# TODO: Remove when SQLx fixes this or provides a way to exclude MySQL

[advisories]
ignore = ["RUSTSEC-2023-0071"]