// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MenuItem = { id: string, section_id: string, name: string, description: string | null, price: number, available: boolean, display_order: number, created_at: string, };

