// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HealthResponse = { status: string, timestamp: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrintSheetResponse = { restaurant_name: string, qr_codes: Array<QrCodeImageResponse>, html_content: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QrCodeImageResponse = { table_id: string, table_name: string, unique_code: string, qr_url: string, qr_image_base64: string, format: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QrCodeResponse = { qr_url: string, table_name: string, unique_code: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserResponse = { id: string, email: string, phone: string | null, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthResponse = { token: string, user: UserResponse, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateOrderResponse = { order_id: string, total_amount: number, status: string, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItemResponse = { menu_item_id: string, menu_item_name: string, quantity: number, price: number, special_requests: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderResponse = { id: string, table_id: string, table_name: string, restaurant_name: string, items: Array<OrderItemResponse>, total_amount: number, status: string, customer_name: string | null, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MenuSectionWithItems = { id: string, restaurant_id: string, name: string, display_order: number, created_at: string, items: Array<MenuItem>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RestaurantMenu = { restaurant_id: string, sections: Array<MenuSectionWithItems>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicMenuItem = { id: string, name: string, description: string | null, price: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicMenuSection = { id: string, name: string, items: Array<PublicMenuItem>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicRestaurantInfo = { name: string, address: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicMenu = { restaurant: PublicRestaurantInfo, sections: Array<PublicMenuSection>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrderItem = { menu_item_id: string, quantity: number, price: number, notes: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Order = { id: string, table_id: string, items: string, total_amount: number, status: string, customer_name: string | null, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Table = { id: string, restaurant_id: string, name: string, unique_code: string, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Restaurant = { id: string, name: string, address: string | null, establishment_year: number | null, google_maps_link: string | null, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MenuSection = { id: string, restaurant_id: string, name: string, display_order: number, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MenuItem = { id: string, section_id: string, name: string, description: string | null, price: number, available: boolean, display_order: number, created_at: string, };

